name: Docker Build e Push no Registry
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Docker GHCR Login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build . --file ./aplicacao/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build image
        run: |
          IMAGE=ghrc.io/${{ github.repository }}/aplicacao:${{ github.sha }}
          docker build \
            --build-arg GH_PACKAGES_TOKEN \
            -t "$IMAGE" \
            aplicacao
          docker push "$IMAGE"
