name: Docker Build e Push no Registry
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: ${{ github.repository }}
      registry: ghcr.io
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Docker GHCR Login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.registry}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        env:
          IMAGE: ghrc.io/${{ github.repository }}/aplicacao:${{ github.sha }}
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./aplicacao
          build-args: GH_PACKAGES_TOKEN
          push: true
          tags: ${{ env.IMAGE }}