name: Criação de Packages
on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Run npm install
        working-directory: pacote
        run: npm install --package-lock-only --ignore-script

      - name: Run npm ci
        run: npm ci && npm test
      
      - name: Publish to GitHub Packages
        working-directory: pacote
        run: npm publish