name: Validar em runtime
on:
  workflow_run:
    workflows: ["Docker Build e Push no Registry"]
    types: [completed]

permissions:
  packages: read
  contents: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      NOME_ALUNO: ${{ vars.NOME_ALUNO }}
  
    steps:
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull and run
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/aplicacao:${{ env.IMAGE_TAG }}
          LOWER_CASE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker pull "$LOWER_CASE"

      - name: Docker Run
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/aplicacao:${{ env.IMAGE_TAG }}
          LOWER_CASE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker run -d --env NOME_ALUNO="${{ env.NOME_ALUNO }}" -p 3000:3000 "$LOWER_CASE"

      - name: Verificação do nome
        run: curl http://localhost:3000/

      
